FCM notification

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -47,6 +47,15 @@ jobs:
     needs: build
 
     steps:
+      - name: Validate Firebase Secret Exists
+        env:
+          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
+        run: |
+          if [ -z "${FIREBASE_SERVICE_ACCOUNT_JSON}" ]; then
+            echo "FIREBASE_SERVICE_ACCOUNT_JSON secret is missing."
+            exit 1
+          fi
+
       - name: Create firebase-service-account.json on VPS
         uses: appleboy/ssh-action@v1.0.3
         with:
